/*
 * Copyright (c) 2024 Quanos Service Solutions GmbH
 */
package de.docware.apps.etk.plugins.customer.daimler.iparts_export.exporter;

/**
 * Alle XML Tags für den Stücklisten - Export
 */
public interface iPartsXMLPartListExporterTags {

    String DTD_FILENAME = "T26DTD01.dtd";
    String EXPORT_HEADER_TIMESTAMP = "yyyy-MM-dd HH:mm:ss.SSSSSS";
    int MAX_COUNT_APS_ENDNUMBER = 3;

    // Tags
    // Allgemein
    String DOCTYPE_TEXT = "<!DOCTYPE SCHNITTSTELLE_PRODUKTDATEN SYSTEM \"" + DTD_FILENAME + "\">";
    String ELEMENT_TEXTE = "TEXTE";
    String ELEMENT_BILDTAFEL = "BILDTAFEL";
    // Datei Header + Frage und Antwort
    String ELEMENT_SCHNITTSTELLE_PRODUKTDATEN = "SCHNITTSTELLE_PRODUKTDATEN";
    String ELEMENT_PRODUKTDATEN = "PRODUKTDATEN";
    String ELEMENT_FRAGE = "FRAGE";
    String ELEMENT_ANTWORT = "ANTWORT";
    String ELEMENT_SEL_FORMAT = "SEL_FORMAT";
    String ELEMENT_SEL_BAUMUSTER = "SEL_BAUMUSTER";
    String ELEMENT_SEL_BAUMUSTER_IDENT = "SEL_BAUMUSTER_IDENT";
    String ELEMENT_SEL_SA_INHALT = "SEL_SA_INHALT";
    String ELEMENT_SEL_SA_IDENT = "SEL_SA_IDENT";
    // Baumuster Daten
    String ELEMENT_BAUMUSTER = "BAUMUSTER";
    String ELEMENT_BAUMUSTER_IDENT = "BAUMUSTER_IDENT";
    String ELEMENT_GUELTIGKEIT = "GUELTIGKEIT";
    String ELEMENT_AS_PRODUKTKLASSE = "AS_PRODUKTKLASSE";
    String ELEMENT_ZUSATZTEXTE = "ZUSATZTEXTE";
    // Aggregate Baumuster zu Fahrzeugbaumuster
    String ELEMENT_AGGREGATE_BAUMUSTER_ID = "AGGREGATE_BAUMUSTER_ID";
    // Freie SA Daten
    String ELEMENT_SA_INHALT = "SA_INHALT";
    // KGTU
    String ELEMENT_KG = "KG";
    String ELEMENT_KG_ID = "KG_ID";
    String ELEMENT_TU = "TU";
    // Teileposition
    String ELEMENT_TEILEPOSITION = "TEILEPOSITION";
    String ELEMENT_PRODUKTGRUPPE = "PRODUKTGRUPPE";
    String ELEMENT_TEILEPOSITIONS_ID = "TEILEPOSITIONS_ID";
    String ELEMENT_TEIL = "TEIL";
    String ELEMENT_CODEBEDINGUNG = "CODEBEDINGUNG";
    String ELEMENT_KOMPONENTEN_ID = "KOMPONENTEN_ID";
    String ELEMENT_PSK_VARIANT = "PSK_VARIANT";
    String ELEMENT_BAUMUSTER_ID = "BAUMUSTER_ID";
    String ELEMENT_AUSFUEHRUNGSART = "AUSFUEHRUNGSART";
    // Ersetzungen
    String ELEMENT_REPLACE_DATEN = "REPLACE_DATEN";
    String ELEMENT_REPLACE_TEIL = "REPLACE_TEIL";
    String ELEMENT_MITLIEFER_DATEN = "MITLIEFER_DATEN";
    String ELEMENT_MITLIEFER_TEIL = "MITLIEFER_TEIL";
    String ELEMENT_MITLIEFERMENGE = "MITLIEFERMENGE";
    // Farben (Variantentabellen)
    String ELEMENT_FARBE = "FARBE";
    String ELEMENT_FARBPOSITIONS_ID = "FARBPOSITIONS_ID";
    // Wahlweise
    String ELEMENT_WAHLWEISE_DATEN = "WAHLWEISE_DATEN";
    // Fußnoten
    String ELEMENT_FUSSNOTE_DATEN = "FUSSNOTE_DATEN";
    String ELEMENT_FUSSNOTE = "FUSSNOTE";
    String ELEMENT_FUSSNOTENTEXTE = "FUSSNOTENTEXTE";
    // Kombinierter Text
    String ELEMENT_KOMBITEXT_DATEN = "KOMBITEXT_DATEN";
    String ELEMENT_KOMBITEXT = "KOMBITEXT";
    // Verwendungsstext
    String ELEMENT_ADDITIONAL_TEXT_DATEN = "ADDITIONAL_TEXT_DATEN";
    String ELEMENT_ADDITIONAL_TEXT = "ADDITIONAL_TEXT";
    // Einsatzdaten
    String ELEMENT_PLANT_INFORMATION_DATEN = "PLANT_INFORMATION_DATEN";
    String ELEMENT_PLANT_INFORMATION = "PLANT_INFORMATION";
    String ELEMENT_AUSREISSER_IDENT = "AUSREISSER_IDENT";
    // Gruppe pro DIALOG Teileposition
    String ELEMENT_GROUPNUMBER = "GROUPNUMBER";
    // Code, die während dem Export aufgesammelt werden
    String ELEMENT_BM_CODE_DESCRIPTION = "BM_CODE_DESCRIPTION";
    String ELEMENT_CODE_DESCRIPTION = "CODE_DESCRIPTION";
    // SAs und SAAs
    String ELEMENT_BAUMUSTER_KG_SA = "BAUMUSTER_KG_SA";
    String ELEMENT_KG_SA = "KG_SA";
    String ELEMENT_BAUMUSTER_SA_SAA_DATEN = "BAUMUSTER_SA_SAA_DATEN";
    String ELEMENT_SA_GRUNDDATEN = "SA_GRUNDDATEN";
    String ELEMENT_SA = "SA";
    String ELEMENT_VERBINDUNGS_SAS = "VERBINDUNGS_SAS";
    String ELEMENT_VERBINDUNGS_SA = "VERBINDUNGS_SA";
    String ELEMENT_CODE = "SA_CODE";
    String ELEMENT_SAA_GRUNDDATEN = "SAA_GRUNDDATEN";
    String ELEMENT_SA_SAA = "SA_SAA";
    String ELEMENT_SA_BENENNUNG = "SA_BENENNUNG";
    String ELEMENT_SAA_BENENNUNG = "SAA_BENENNUNG";
    String ELEMENT_BAUMUSTER_BK_DATEN = "BAUMUSTER_BK_DATEN";
    String ELEMENT_BAUMUSTER_BK = "BAUMUSTER_BK";
    // Federmapping
    String ELEMENT_BM_SPRING_MAPPING = "BM_SPRING_MAPPING";
    String ELEMENT_SPRING_TABLE = "SPRING_TABLE";
    String ELEMENT_SPRING_PART = "SPRING_PART";
    String ELEMENT_SPARE_PART = "SPARE_PART";
    // Alternativteil
    String ELEMENT_ALTERNATIVE_PART_DATA = "ALTERNATIVTEIL_DATEN";
    // Leitungssatz-BK
    String ELEMENT_WIRE_HARNESS_DATEN = "WIRE_HARNESS_DATEN";
    String ELEMENT_WIRE_HARNESS = "WIRE_HARNESS";
    String ELEMENT_WIRE_HARNESS_CONTENT = "WIRE_HARNESS_CONTENT";
    String ELEMENT_WIRE_HARNESS_COMPONENT = "WIRE_HARNESS_COMPONENT";
    // PRIMUS Daten & Custom Properties
    String ELEMENT_ADDITIONAL_PART_DATA = "ADDITIONAL_PART_DATEN";
    String ELEMENT_ADDITIONAL_PART_INFORMATION = "ADDITIONAL_PART_INFORMATION";
    String ELEMENT_ADDITIONAL_PART_VALUES = "ADDITIONAL_PART_VALUES";
    // EinPAS Daten
    String ELEMENT_EINPAS_DATA = "EINPAS_DATEN";
    String ELEMENT_EINPAS_NODE = "EINPAS_NODE";

    // Attribute
    // Allgemein
    String ATTRIBUTE_SPRACH_ID = "SPRACH_ID";
    String ATTRIBUTE_BENENNUNG = "BENENNUNG";
    String ATTRIBUTE_LENKUNG = "LENKUNG";
    // Datei Header + Frage und Antwort
    String ATTRIBUTE_IF_IDENT = "IF_IDENT";
    String ATTRIBUTE_EMPFAENGER = "EMPFAENGER";
    String ATTRIBUTE_FTP_ADRESSE = "FTP_ADRESSE";
    String ATTRIBUTE_USER = "USER";
    String ATTRIBUTE_SEL_FORMAT_ID = "SEL_FORMAT_ID";
    String ATTRIBUTE_SEL_BAUMUSTER_ID = "SEL_BAUMUSTER_ID";
    String ATTRIBUTE_SEL_EINSATZ = "SEL_EINSATZ";
    String ATTRIBUTE_SEL_SA_ID = "SEL_SA_ID";
    // Produktstammdaten
    String ATTRIBUTE_NUR_GUELTIG_IN_LAENDERN = "NUR_GUELTIG_IN_LAENDERN";
    String ATTRIBUTE_UNGUELTIGE_LAENDER = "UNGUELTIGE_LAENDER";
    // Baumuster
    String ATTRIBUTE_BAUMUSTERART = "BAUMUSTERART";
    String ATTRIBUTE_MARKTEINFUEHRUNGSTERMIN_AB = "MARKTEINFUEHRUNGSTERMIN_AB";
    String ATTRIBUTE_MARKTEINFUEHRUNGSTERMIN_BIS = "MARKTEINFUEHRUNGSTERMIN_BIS";
    String ATTRIBUTE_PS = "PS";
    String ATTRIBUTE_KW = "KW";
    String ATTRIBUTE_DOKUMETHODE = "DOKUMETHODE";
    String ATTRIBUTE_BAUMUSTER_ID = "BAUMUSTER_ID";
    String ATTRIBUTE_EINSATZ = "EINSATZ";
    String ATTRIBUTE_SELECTED_PSK_VARIANTS = "SELECTED_PSK_VARIANTS";
    String ATTRIBUTE_ZUSATZTEXT = "ZUSATZTEXT";
    String ATTRIBUTE_VERKAUFSBEZEICHNUNG = "VERKAUFSBEZEICHNUNG";
    String ATTRIBUTE_BEMERKUNG = "BEMERKUNG";
    String ATTRIBUTE_DATUM_DOKUMENTATION = "DATUM_DOKUMENTATION";
    String ATTRIBUTE_MODELJAHRCODE = "MODELJAHRCODE";
    String ATTRIBUTE_ENDNUMMER_AB_BASE = "ENDNUMMER_AB";
    String ATTRIBUTE_ENDNUMMER_BIS_BASE = "ENDNUMMER_BIS";
    // KGTU
    String ATTRIBUTE_TU_ID = "TU_ID";
    String ATTRIBUTE_TU_MODULNUMMER = "MODULNUMMER";
    //Teileposition
    String ATTRIBUTE_BILD_ID = "BILD_ID";
    String ATTRIBUTE_BILD_REV_ID = "BILD_REV_ID";
    String ATTRIBUTE_MENGE = "MENGE";
    String ATTRIBUTE_GETRIEBE = "GETRIEBE";
    String ATTRIBUTE_STRUKTURSTUFE = "STRUKTURSTUFE";
    String ATTRIBUTE_TEIL_ID = "TEIL_ID";
    String ATTRIBUTE_ORIGINAL_TEIL_ID = "ORIGINAL_TEIL_ID";
    String ATTRIBUTE_TEIL_ID_FORMATIERT = "TEIL_ID_FORMATIERT";
    String ATTRIBUTE_ES1 = "ES1";
    String ATTRIBUTE_LAUFENDENUMMER = "LAUFENDENUMMER";
    String ATTRIBUTE_GENERIC_LOCATION = "GENERIC_LOCATION";
    // PSK Attribute
    String ATTRIBUTE_PSK_PART = "PSK_PART";
    String ATTRIBUTE_PSK_SUPPLIER_NO = "PSK_SUPPLIER_NO";
    String ATTRIBUTE_PSK_MANUFACTURER_NO = "PSK_MANUFACTURER_NO";
    String ATTRIBUTE_PSK_SUPPLIER_PART_NO = "PSK_SUPPLIER_PART_NO";
    String ATTRIBUTE_PSK_MANUFACTURER_PART_NO = "PSK_MANUFACTURER_PART_NO";
    String ATTRIBUTE_PSK_IMAGE_NO_EXTERN = "PSK_IMAGE_NO_EXTERN";
    String ATTRIBUTE_PSK_PSK_REMARK = "PSK_PSK_REMARK";
    String ATTRIBUTE_PSK_NATO_NO = "PSK_NATO_NO";
    // Farben (Variantentabellen)
    String ATTRIBUTE_ES2 = "ES2";
    String ATTRIBUTE_FARB_KZ = "FARB_KZ";
    // Fußnoten
    String ATTRIBUTE_FUSSNOTEN_ID = "FUSSNOTEN_ID";
    String ATTRIBUTE_FUSSNOTENPOSITIONS_ID = "FUSSNOTENPOSITIONS_ID";
    String ATTRIBUTE_FUSSNOTENTEXT = "FUSSNOTENTEXT";
    // Kombinierter Text
    String ATTRIBUTE_KOMBI_TEXT = "KOMBI_TEXT";
    // Einsatzdaten
    String ATTRIBUTE_TYPE = "TYPE";
    String ATTRIBUTE_PLANT = "PLANT";
    String ATTRIBUTE_WMI = "WMI";
    String ATTRIBUTE_HAUPTIDENT = "HAUPTIDENT";
    String ATTRIBUTE_EINSATZTERMIN = "EINSATZTERMIN";
    String ATTRIBUTE_STEUERCODE = "STEUERCODE";
    String ATTRIBUTE_AUSREISSER_IDENT_ID = "AUSREISSER_IDENT_ID";
    // Code, die während dem Export aufgesammelt werden
    String ATTRIBUTE_CODE_ID = "CODE_ID";
    String ATTRIBUTE_DATUM_GUELTIG_AB = "DATUM_GUELTIG_AB";
    String ATTRIBUTE_DATUM_GUELTIG_BIS = "DATUM_GUELTIG_BIS";
    // freie SA Attribute
    String ATTRIBUTE_SA_IDENT = "SA_IDENT";
    String ATTRIBUTE_SAA_IDENT = "SAA_IDENT";
    String ATTRIBUTE_BK_IDENT = "BK_IDENT";
    // Leitungssatz-BK
    String ATTRIBUTE_REFERENCE_NUMBER = "REFERENCE_NUMBER";
    String ATTRIBUTE_CONNECTOR_NUMBER = "CONNECTOR_NUMBER";
    String ATTRIBUTE_PART_NUMBER_TYPE = "PART_NUMBER_TYPE";
    // Custom Properties
    String ATTRIBUTE_API_DESCRIPTION = "DESCRIPTION";
    String ATTRIBUTE_API_TYPE = "TYPE";
    String ATTRIBUTE_API_VALUE = "VALUE";
    // EINPAS Attribute
    String ATTRIBUTE_EINPAS_MAIN_GROUP = "HG";
    String ATTRIBUTE_EINPAS_GROUP = "G";
    String ATTRIBUTE_EINPAS_TECHNICAL_SCOPE = "TU";
    String ATTRIBUTE_EINPAS_VERSION = "VERSION";

    // Fahrzeug-Navigations-TU
    String ATTRIBUTE_CG = "CG";
    String ATTRIBUTE_CSG = "CSG";
    String ATTRIBUTE_PRODUCT_ID = "PRODUCT_ID";
    String ATTRIBUTE_MODEL_ID = "MODEL_ID";
}
